import NavbarServer from "@/components/layout/NavbarServer";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/layout/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import ConditionalLayoutWrapper from "@/components/layout/ConditionalLayoutWrapper";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="id">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ConditionalLayoutWrapper
          navbar={<NavbarServer />}
          footer={<Footer />}
        >
          {children}
        </ConditionalLayoutWrapper>
      </body>
    </html>
  );
}
